apiVersion: apps/v1
kind: Deployment
metadata:
  name: diploma-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diploma-app
  template:
    metadata:
      labels:
        app: diploma-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: diploma-app
          image: sojasac/diploma-app:latest   # твой образ в Docker Hub
          imagePullPolicy: Always
          ports:
            - containerPort: 8080