apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8080 # публичный порт
      targetPort: 3000 # порт внутри Pod’а Grafana
  selector:
    app.kubernetes.io/name: grafana