name: Full CI/CD to EKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # СБОРКА ИЗ docker/Dockerfile
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/diploma-app:latest -f docker/Dockerfile docker/

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diploma-app:latest

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Connect to EKS cluster
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Update container image in deployment
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/diploma-app:latest|g" k8s/diploma_app-deployment.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Apply Argocd manifests
        run: |
          kubectl apply -f argocd/application.yaml
