name: Full CI/CD to EKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем проект
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Логинимся в Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Собираем Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/diploma-app:latest docker/Dockerfile .

      # 4. Пушим в Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diploma-app:latest

      # 5. Устанавливаем AWS CLI 
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. Логин в EKS (kubectl)
      - name: Connect to EKS cluster
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      # 7. Обновляем Docker image в YAML
      - name: Update container image in deployment
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/diploma-app:latest|g" k8s/deployment.yaml

      # 8. Применяем манифесты в EKS
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/