grafana:
  ingress:
    enabled: false
  env:
    GF_SERVER_HTTP_ADDR: "0.0.0.0"
    GF_SERVER_ROOT_URL: "/grafana/"
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"

argo-cd:
  server:
    extraArgs:
      - --insecure
      - --rootpath=/argocd
      - --listen=:80
    config:
      url: "/argocd/"
      server.basehref: /argocd
      server.rootpath: /argocd
      application.instanceLabelKey: argocd.argoproj.io/instance
    ingress:
      enabled: false
    service:
      type: ClusterIP
